_commit: a87baf8
_src_path: gh:yevheniidehtiar/python-scaffold
author_email: jules@example.com
author_name: Jules
project_description: A new Python project
project_name: my-new-project
project_type: package
project_url: https://github.com/user/my-new-project
python_version: '3.10'
typing: optional
with_conventional_commits: true
with_typer_cli: false
