"""Generate templates/components/_icons.html from static/icons/*.svg.

Run from the repository root after adding an icon (from the pinned Lucide release)
to src/hyperadmin/static/icons/:

    uv run python scripts/generate_icon_macro.py
"""

import re
import sys
from pathlib import Path

root = Path("src/hyperadmin")
icons = {}
for svg in sorted((root / "static/icons").glob("*.svg")):
    text = svg.read_text().strip().replace(" />", "/>")
    svg.write_text(text + "\n")
    body = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", text, flags=re.DOTALL)
    icons[svg.stem] = body.replace("'", "\\'")

lines = [
    "{#-",
    "    Lucide icons (ISC licence) inlined as SVG, so they take the text colour and cost",
    "    no request. Generated by scripts/generate_icon_macro.py from static/icons/*.svg:",
    "    add the .svg there and rerun the script; do not edit this file by hand.",
    "",
    "    Usage:",
    '        {%- from "components/_icons.html" import icon -%}',
    "        {{ icon('pencil') }}                        decorative, aria-hidden",
    "        {{ icon('chevron-right', 'ha-icon--sm ha-icon--mirror') }}",
    "-#}",
    "{%- set icon_paths = {",
]
for name, body in icons.items():
    lines.append(f"    '{name}': '{body}',")
lines += [
    "} -%}",
    "",
    "{%- macro icon(name, class='') -%}",
    (
        '<svg class="ha-icon{{ \' \' ~ class if class }}" viewBox="0 0 24 24" fill="none"'
        ' stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"'
        ' aria-hidden="true" focusable="false">{{ icon_paths.get(name, \'\') | safe }}</svg>'
    ),
    "{%- endmacro -%}",
    "",
]
(root / "templates/components/_icons.html").write_text("\n".join(lines))
sys.stdout.write(f"{len(icons)} icons\n")
