import anyio
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel import Field, SQLModel
from unittest.mock import MagicMock
from fastapi.templating import Jinja2Templates

from hyperadmin.adapters.sqlmodel import SQLModelAdapter
from hyperadmin.core.model import ModelAdmin
from hyperadmin.core.options import AdminOptions
from hyperadmin.core.registry import site
from hyperadmin.main import Admin
from hyperadmin.routing import create_admin_router


class Product(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str
    price: float


class ProductAdmin(ModelAdmin):
    adapter_class = SQLModelAdapter


@pytest.fixture(autouse=True)
def cleanup_registry():
    """Ensures the site registry is clean before and after each test."""
    site._registry = {}
    yield
    site._registry = {}


@pytest.fixture
async def engine():
    """Provides a temporary, in-memory SQLite database engine for tests."""
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)
    return engine


@pytest.fixture
def client_factory():
    """Provides a factory for creating a TestClient with a clean database."""

    def _client_factory(options: AdminOptions = None):
        app = FastAPI()
        engine = create_async_engine("sqlite+aiosqlite:///:memory:")

        async def setup_database():
            async with engine.begin() as conn:
                await conn.run_sync(SQLModel.metadata.create_all)

        anyio.run(setup_database)

        admin = Admin(app=app, create_tables=False, engine=engine)
        site.register(Product, ProductAdmin, options=options or AdminOptions())
        admin.mount(path="/admin")

        return TestClient(app)

    return _client_factory


async def test_create_admin_router_default_options(engine, anyio_backend):
    """Tests that all CRUD routes are generated by default."""
    site.register(Product, ProductAdmin)
    admin_class = site._registry[Product]
    admin_instance = admin_class(Product)
    mock_templates = MagicMock(spec=Jinja2Templates)
    router = create_admin_router(
        model=Product,
        admin_class=admin_class,
        admin_instance=admin_instance,
        options=AdminOptions(),
        engine=engine,
        templates=mock_templates,
    )

    routes = {route.name for route in router.routes}
    assert "product-list" in routes
    assert "product-create" in routes
    assert "product-create-form" in routes
    assert "product-detail" in routes
    assert "product-update" in routes
    assert "product-update-form" in routes
    assert "product-delete" in routes


async def test_create_admin_router_disabled_views(engine, anyio_backend):
    """Tests that routes are not generated for disabled views."""
    options = AdminOptions(can_create=False, can_delete=False)
    site.register(Product, ProductAdmin, options=options)
    admin_class = site._registry[Product]
    admin_instance = admin_class(Product)
    mock_templates = MagicMock(spec=Jinja2Templates)
    router = create_admin_router(
        model=Product,
        admin_class=admin_class,
        admin_instance=admin_instance,
        options=options,
        engine=engine,
        templates=mock_templates,
    )

    routes = {route.name for route in router.routes}
    assert "product-list" in routes
    assert "product-create" not in routes
    assert "product-create-form" not in routes
    assert "product-detail" in routes
    assert "product-update" in routes
    assert "product-update-form" in routes
    assert "product-delete" not in routes


def test_admin_integration_with_disabled_views(client_factory):
    """Tests the integration with the main Admin class and FastAPI app."""
    client = client_factory(options=AdminOptions(can_create=False, can_list=False))

    # The list view should be disabled
    response = client.get("/admin/product")
    assert response.status_code == 404

    # The create form view should be disabled
    response = client.get("/admin/product/create")
    assert response.status_code == 404

    # The detail view should be enabled
    # We expect a 404 because the item doesn't exist, but this shows the route exists.
    response = client.get("/admin/product/1")
    assert response.status_code == 404


def test_admin_integration_with_default_options(client_factory):
    """Tests that default options are used when none are provided."""
    client = client_factory()  # No options provided, so defaults are used

    response = client.get("/admin/product")
    assert response.status_code == 200
    assert "Product" in response.text
