name: Test
permissions:
  contents: read

on:
  push:
    branches:
      - develop
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        resolution: ["highest", "lowest-direct"]

    name: Python ${{ matrix.python-version }} (resolution=${{ matrix.resolution }})

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash

      - name: Install dependencies
        run: uv sync --all-extras --python ${{ matrix.python-version}} --resolution ${{ matrix.resolution }}

      - name: Lint package
        run: uv run poe lint

      - name: Test package
        run: uv run poe test:unit

      - name: Security checks
        run: uv run poe security-check

      - name: E2E Test package
        run: uv run poe test:e2e

  test-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.12"
            resolution: "highest"
          - python-version: "3.10"
            resolution: "lowest-direct"

    name: Python ${{ matrix.python-version }} (resolution=${{ matrix.resolution }})

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash

      - name: Install dependencies
        run: uv sync --all-extras --python ${{ matrix.python-version}} --resolution ${{ matrix.resolution }}

      - name: Lint package
        run: uv run poe lint

      - name: Test package
        run: uv run poe test:unit

      - name: Security checks
        run: uv run poe security-check
